# Discussion

This study assesses patterns of copper emission, occurrence, monitoring and distribution in two marine Arctic Aggegrate Exposure Pathway case studies. Exactly how much of a threat copper poses and more importantly will pose to Arctic marine ecosystems is uncertain. In the Baltic sea, an enclosed, heavily developed, and more thoroughly assessed marine area, copper concentrations exceed quality thresholds across the sea [@helcomCopperHELCOMCore2023]. Climate change is expected to increase both copper emissions from anthropogenic and natural runoff and antifoulants, but also organic carbon, which complexes bioavailable copper and thus reduces its toxicity, as well as raising sea levels, which may dilute existing copper. [@helcomCopperHELCOMCore2023]. Arctic ecosystems are expected to be particularly adversely affected by climate change [@ipccClimateChange20222023], but whether increased copper-emitting industry in the area will follow (due to easier access) or wane (due to retreating permafrost and thus instability in infrastructure [@krogerSocioecologicalCrisesGlobal2023]) is not yet certain. A growing demand for copper is near-certain [@pietrzykTrendsGlobalCopper2018a], but how much of this will result in copper emissions to the environment (as opposed to embedded copper in infrastructure and products [@comberSourcesCopperEuropean2023]) is far less so. Based on studies of Repparfjord's tailings [@sternalImpactSubmarineCopper2017; @pedersenMetalSpeciationHistoric2017], contamination from the Submarine Tailings Disposal (STD) was contained to a small area of the fjord by local geography, but it is not guaranteed that this will continue to be the case with future disposal there or elsewhere in the Arctic. Even aquaculture, a substantial source of localised copper emissions has largely displaced use of copper antifoulants with tralopyril and zinc-based agents [@norwegianenvironmentagencyBiociderSomBrukes2025]; thus, despite projected growth [@dnvOceansFuture20502021] it may not continue to be an important source of the metal. It is uncontroversial that the Arctic will face growing anthropogenic stress and environmental degradation in coming years [@thyrringHorizonScanArctic2025], but it is unclear how much of a role copper exposure will play in these.

Despite copper's extensive representation in both monitoring data (in Norway, it is, by number of samples, the single most monitored stressor) [@norwegianenvironmentagencyVannmiljo2026] and scientific literature more generally [@grandjeanMatthewEffectEnvironmental2011], acquiring sufficient data to understand the distribution and temporal patterns in contamination in these Arctic case study areas was challenging. The initial systematic literature review set out to collect data covering the entire Arctic region to support more conceptual AEPs scoped to the whole area. However, during data collection it was realised that individual case study areas more accurately reflected the distribution patterns of copper. Given that Repparfjord is one of the most (famously) copper-contaminated sites in Norway, extremely little data on copper in biota and exposure media existed, and where it did exist, some suspected errors in the orders-of-magnitude-degree were found. This was surprising, although we must note that it is possible that more data on the area were available in the grey literature.

Emissions data was similarly difficult to acquire. Although [@comberSourcesCopperEuropean2023]'s assessment of copper sources provided an excellent source for understanding typical sources and magnitudes of copper emissions, spatially-specific data were only partially available, meaning that many sources identified by @comberSourcesCopperEuropean2023 as important (for example brake wear particles) had to be included as unquantified source KESs. Reported data from the Pollutant Release and Transfer Register (PRTR) was available to the facility level [@norwegianenvironmentagencyNorwegianPRTRNorske2025], but many facilities in the study area reported no or unexpectedly low copper emissions. Wastewater Treatment Plant copper emissions (expected to be an important source considering the area's lack of combined sewers and primary-only treatment) were unavailable for any settlement in the county, requiring the use of population-averaged data from a larger town's plant. Emissions data for aquaculture facilities in the municipality were surprisingly complete (see Fig 12, SI), but the lack of available information on how these values were modelled and whether they represent feed and/or antifoulant emissions make their overall value limited.

The Aggregate Exposure Pathway conceptual model [@tanRefiningAggregateExposure2018; @teeguardenCompletingLinkExposure2016; @tanAggregateExposurePathways2018] provided a useful means for visualising concentrations and flows of copper in two distinct copper-contaminated Arctic sites. Our refinement of @pengAggregateExposurePathways2022's approach to displaying Weight of Evidence (WoE) assessments for each Key Exposure State (KES) and Key Transitional Relationship (KTR) allows for simple, intuitive visualisation of the magnitude and evidence associated with each element.

Our determination that Arctic copper pollution was highly site-specific was borne out by available data. Elevated copper concentrations (both in sediment and in biota) in Hammerfest were present in the vicinity of a number of point sources (Melkøya LNG plant, some aquaculture facilities) but appeared generally low across the study area. In Repparfjord, copper concentrations were extremely high in sediment (especially at the inner fjord), and average tissue concentrations higher, but these elevated concentrations fell off quickly, and no corresponding pattern of higher sediment concentration to the South-East was seen in the Hammerfest system. The use of non-spatially specific data for river water/sediment and fjord water in Repparfjord weakened overall empiricism of the system; however, as the sediment/tailings are expected to be the main source of contamination, this may not severely weaken any conclusions that can be drawn. 

Some aspects of the AEP framework presented challenges. Monitoring data on copper exposure to the most sensitive tissues (gills, sensory organs) and life stages (typically early life) was not often available, which resulted in the AEPs terminating Target Site Exposure (TSE) KESs based on livers and muscles (in fish), whole soft tissues (in mussels), and other potential sites of bioaccumulation (macroalgae shoot tips, crab muscle and hepatopancreas). Furthermore, copper toxicity at these tissues is mediated by complex interactions between bioavailable fractions, sensitive tissues, other ligands competing for copper ions, and other physico-chemical parameters [@liaoToxicityMechanismsBioavailability2023; @ditoroBioticLigandModel2001]. However, the vast majority of data reported was from samples processed by acid digestion, this "Total" fraction not properly representing actual bioavailable copper. This degree of biological and chemical complexity could be represented on an AEP (@tanRefiningAggregateExposure2018 suggests joining multiple AEPs together where a stressor is transformed). However so doing would require significant changes to the existing AEPs and considerable additional data; the degree to which copper's chemical and biological complexity could be represented as an AEP before it would cease to be an AEP is uncertain.

A further challenge was more prosaic: depicting complex, multi-source emission patterns as a network diagram presents constraints in terms of visual complexity. AEP 1 (Hammerfest)'s 6 emissions sources already represented a degree of category lumping, but even this generated a dense network of KTR arrows between nodes, making visual interpretation more difficult. Prior AEPs have tended to consider [@pengAggregateExposurePathways2022; @hinesQuantitativeSourcetooutcomeCase2019; @sanganyadoAggregateExposurePathways2024; @jeongIntegratingAggregateExposure2024] xenobiotic substances from a small range of emissions sources. Copper, which is ubiquitous, essential, natural, [@wrightBacterialEvolutionaryPrecursors2021; @tangMolecularEvolutionCu2025; @lutsenkoMammalianCopperHomeostasis2025], and moved through the environment by a range of biotic and abiotic processes, is less amenable to the format, which is perhaps more suited to displaying scenarios where the causal chain of emission to exposure and target sites is more distinct.

The WoE framework developed by @pengAggregateExposurePathways2022 and @oecdConsiderationsAssessingRisks2018 provided an effective and intuitive framework for assessing evidence for copper's occurence and flows. However, because copper is ubiquitous, its presence in any given KES and indeed its movement across KTR was generally highly plausible. Likewise, quantifying the essentiality of any given KES was often not meaningful; the presence of copper at any KES is axiomatic but not necessarily dependent on any upstream KES. Because the scope of the study literature review covered only papers that reported copper concentrations but not models or flow rates, KES and KTR are uniformly scored as a 1/3 for Quantification. In some cases, a score of 1-3 was judged to provide insufficient discrimination between the weight of different lines and forms of evidence, and a more detailed scoring system may be more useful. 

Ultimately, we found the AEP concept a useful way of organising exposure data, although its use presented a number of challenges that we were not fully able to address. The use of systematic literature review, which initially seemed apposite for asessing copper pollution across the Arctic, was scoped over-broadly; this impaired our ability to provide sufficient evidence in terms of KES/KTR quantification (i.e. relevant numerical models, if they exist). Additionally, as much emissions data and information relevant to the Repparfjord is described in grey literature, this was not initially captured by our scientific literature-scoped review. A future review of copper pollution in the Arctic should focus on a subset of the region (perhaps sites of current or planned copper mines) in order to be able to assess existing evidence sufficiently thoroughly. More complete emissions, occurrence and biota data may be needed before such an assessment can be conducted with more certainty, but in the interim, the AEP provides a useful means for representing knowledge and uncertainty. 