project:
  type: website
  output-dir: docs
  
website:
  title: "EXPECT Copper AEP"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Article"
        contents:
          - href: index.qmd
            text: "Manuscript Draft"
      - section: "Notebooks"
        contents:
          - href: qmd/NB01-pipeline.qmd
            text: "NB01 - Analysis Pipeline"
            icon: journal-code
          - href: qmd/NB02-vannmiljo.qmd
            text: "NB02 - Vannmiljø"
            icon: journal-code
          - href: qmd/NB02-vannmiljo-qc.qmd
            text: "NB02 - Vannmiljø QC"
            icon: journal-code
          - href: qmd/NB03-qc.qmd
            text: "NB03 - QC"
            icon: journal-code
          - href: qmd/NB03-visualisation.qmd
            text: "NB03 - Visualisation"
            icon: journal-code
          - href: qmd/NB04-map.qmd
            text: "NB04 - Map"
            icon: journal-code
          - href: qmd/NB05-network.qmd
            text: "NB05 - Network Diagram"
            icon: journal-code
          - href: qmd/NB06-WoE.qmd
            text: "NB06 - Weight of Evidence"
            icon: journal-code
          - href: qmd/NB07-emissions.qmd
            text: "NB07 - Emissions"
            icon: journal-code
          - href: qmd/NB08-ecology.qmd
            text: "NB08 - Ecology"
            icon: journal-code
          - href: qmd/NBXX-reparfjorden.qmd
            text: "NBXX - Repparfjorden"
            icon: journal-code
      - section: "Appendices"
        contents:
          - href: qmd/AP01-review-protocol.qmd
            text: "AP01 - Review Protocol"
            icon: file-earmark-plus
          - href: qmd/AP02-acknowledgements.qmd
            text: "AP02 - Acknowledgements"
            icon: file-earmark-plus

# acronyms:
#   keys:
#     - shortname: AEP
#       longname: Aggregate Exposure Pathway

execute:
  freeze: auto

format:
  html:
    code-fold: true
    code-overflow: wrap
    fig-format: svg
    toc: true
    grid:
      sidebar-width: 400px
    monofont: "Fira Code"
    fig-width: 12

authors:
  - name: Sam Welch
    affiliation: Norwegian Institute for Water Research
    roles: [conceptualization, data curation, formal analysis, investigation, methodology, software, validation, visualization]
    corresponding: true
    email: sam.welch@niva.no
    orcid: 0000-0003-4743-4562
  - name: Knut Erik Tollefsen
    affiliations:
      - name: Norwegian Institute for Water Research
        city: Oslo
        country: Norway
        url: https://niva.no/en
      - name: Norwegian University of Life Sciences
        city: Ås
        country: Norway
        url: https://www.nmbu.no/en 
    roles: writing
    corresponding: false
  - name: Pierre Blévin
    affiliation:
      name: Akvaplan-NIVA AS
      city: Tromsø
      country: Norway
      url: https://akvaplan.no/en 
    roles: writing
    corresponding: false
  - name: Anita Evenset
    affiliation:
      name: Akvaplan-NIVA AS
      city: Tromsø
      country: Norway
      url: https://akvaplan.no/en
    roles: writing
    corresponding: false
  - name: Camden Karon Klefbom
    affiliation:
      name: Norwegian Institute for Water Research
      city: Oslo
      country: Norway
      url: https://niva.no/en
    roles: writing
    corresponding: false
    
bibliography: references.bib
number-sections: true

comments:
  hypothesis: true # enables comments using a 3rd party service

engine: knitr