website:
  title: "EXPECT Copper AEP"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Article"
        contents:
          - href: index.qmd
            text: "Manuscript Draft"
      - section: "Notebooks"
        contents:
          - href: docs/NB01-qc.qmd
            text: "NB01 - Data QC"
            icon: journal-code
          - href: docs/NB02-vannmiljo.qmd
            text: "NB02 - Vannmiljø"
            icon: journal-code
          - href: docs/NB03-visualisation.qmd
            text: "NB03 - Visualisation"
            icon: journal-code
          - href: docs/NB04-map.qmd
            text: "NB04 - Map"
            icon: journal-code
          - href: docs/NB05-network.qmd
            text: "NB05 - Network Diagram"
            icon: journal-code
          - href: docs/NB07-emissions.qmd
            text: "NB07 - Emissions"
            icon: journal-code
          - href: docs/NB08-ecology.qmd
            text: "NB08 - Ecology"
            icon: journal-code
      - section: "Appendices"
        contents:
          - href: docs/AP01-review-protocol.qmd
            text: "AP01 - Review Protocol"
            icon: file-earmark-plus
          - href: docs/AP02-acknowledgements.qmd
            text: "AP02 - Acknowledgements"
            icon: file-earmark-plus

acronyms:
  keys:
    - shortname: AEP
      longname: Aggregate Exposure Pathway

execute:
  freeze: auto