---
title: "Appendix 02 - Acknowledgements"
author: "Sam Welch"
date: last-modified
---


# EWMA project/Kristine Bondo Pedersen

::: callout-note 
## Re: The impact of submarine copper mine tailing disposal from the 1970s on Repparfjorden, northern Norway

Hi Sam and a Happy New Year,

Sorry about the late reply – I managed to completely forget about your first email and then go on an extended Christmas holiday!

I have been looking into the archives and managed to find an excel sheet with all the data – I hope this is what you are looking for! And if you do use the data in a publication would you be kind and acknowledge the EWMA project, which resulted in all this data! And also not share it with people outside NIVA (I would have to double-check how Akvaplan does this formally).

Let me know if you need me to dig for any other data from the project!

Best wishes,

Kristine 

:::

# Bioaccumulation of metals (Cd, Cu, Ni, Pb and Zn) in suspended cultures of blue mussels exposed to different environmental conditions

Marie Maar - Provided raw data on request 

# Copper in Agriculture Sales Data
- Collected by Matilsynet
- Referred by Roger Holten

# Distribution pattern of mercury in northern Barents Sea and Eurasian Basin

Stephen Gustav Kohler provided full data on request.

# Determination of Nanoparticles and Elements in Blue Mussels (Mytilus edulis) along the Norwegian Coastline 

Are Sæle Bruvold provided raw data on request.

## At NIVA

# Consultation on Literature Reviews

Aina Charlotte Weinberg, Maria Hultman, Max Nawarth

## MD

>Hei 
Din henvendelse REQ0014380 - Copper Pollution/Use Statistics er oppdatert med følgende:
Beklager sent svar. Legger ved tall for utvalgte kobberstoffer i produktregisteret. Stoffene er fra liste som vi har brukt i forbindelse med statistikken for kobber i notimpregnering i akvakultur. Du kjenner kanskje tallene fra HI rapporter etc. Det er godt mulig det er flere kobberstoffer i registeret. Har du forslag til stoffer vi kunne sjekke, eller bare søke kjapt å se om det er noe? (altså andre enn de i listen)
Det er også mulig å dele opp bransjer og typer mye mer. Du kan se mer om produkttypene våre og bransjekodene våre på hjemmesidene. Jeg brukte nå en hovedgruppering for at du kunne få en bilde av hva vi har av disse kobberstoffene.
Mer spesifikt for typer og bransjer kan du spørre om. Det er da også mulig at det blir uoff tall særlig om du også spesifiserer spørsmål om stoffene.
Lagde også en med mengder per stoff.
Tallene per stoff kan være at noen er unntatt offentlighet.
Vil du se fordelingen per stoff så kan jeg sende deg en kryptert fil.
Da trenger jeg telefonnummeret så jeg kan sende deg passord.(så sender jeg en mail med en separat fil)



## Other

Yasmina Gopali - Copper Association
Kevin Brix - Advice on copper environmental chemistry
