---
title: "Notebook 08 - Ecology and Biota"
author: "Sam Welch"
date: "2025.11.25"
lightbox: true
format:
  html:
    grid:
      body-width: 1500px
      sidebar-width: 0px
    page-layout: full
    code-fold: true
    max-width: 4500px
    fig-format: svg
    toc: true
---

*A holding space for relevant data on biota diets and ADME*.

The black-legged kittiwake is a small pelagic gull with a global population of 6–8 million pairs of which 120000 pairs breed on the west coast of Spitsbergen, Svalbard (Frederiksen et al., 2012). The kittiwakes breeding on Svalbard migrate towards Greenland and Canada in the end of October, overwintering in a widespread area in the North Atlantic between November and April (Frederiksen et al., 2012, Schultner et al., 2014). Kittiwakes have a varied diet, preying on small pelagic fish like polar cod (Boreogadus saida) and capelin (Mallotus villosus), as well as pelagic amphipods (Themisto spp.) and euphausiids (Thysanoessa spp.) (Mehlum and Gabrielsen, 1993). Other small fish species (15–20 cm), polychaetes and pteropods are also frequent in the diet of kittiwakes (Hatch, 2013). Seasonal and spatial variations in kittiwake diet occur (Anker-Nilssen et al., 2000, Lønne and Gabrielsen, 1992). During the breeding season, adult kittiwakes in Kongsfjorden feed mainly on polar cod and krill (Thysanoessa inermis) (Mehlum and Gabrielsen, 1993).

https://www.sciencedirect.com/science/article/pii/S0048969714013801?via=ihub#s0010