# Create readable column names from ICES codes ----
convert_ICES_readable <- function(dataframe, .keep = "all") {
  dataframe |>
    dplyr::mutate(
      Monitoring_Programme = MPROG,
      Purpose_Of_Monitoring = PURPM,
      Country = Country,
      Reporting_Laboratory = RLABO,
      Station_Name = STATN,
      Monitoring_Year = MYEAR,
      Date = DATE,
      Latitude = Latitude,
      Longitude = Longitude,
      Species = Species,
      Sex_Code = SEXCO,
      Number_Of_Individuals_In_Pool = NOINP,
      Matrix = MATRX,
      Number_Of_Diseases = NODIS,
      Parameter_Group = PARGROUP,
      Parameter = PARAM,
      Basis = BASIS,
      Quality_Flag = QFLAG,
      Value = Value,
      Measurement_Unit = MUNIT,
      Value_Flag = VFLAG,
      Detection_Limit = DETLI,
      Limit_Of_Quantification = LMQNT,
      Uncertainty = UNCRT,
      Method_Uncertainty = METCU,
      Analytical_Laboratory = ALABO,
      Reference_Sample_Key = REFSK,
      Method_Storage = METST,
      Method_Pre_Treatment = METPT,
      Method_Prep_And_Separation = METPS,
      Method_Final_Prep = METFP,
      Method_Chemical_Extraction = METCX,
      Method_Of_Analysis = METOA,
      Formula = FORML,
      Test_Organism = `Test Organism`,
      Sample_Type = SMTYP,
      Subsample_Number = SUBNO,
      Bulk_ID = BULKID,
      Final_Flag = FINFL,
      Data_Check_Flags = DCFLGs,
      Table_Analysis_ID = tblAnalysisID,
      Table_Parameter_ID = tblParamID,
      Table_Bio_ID = tblBioID,
      Table_Sample_ID = tblSampleID,
      Depth_Upper = DEPHU,
      Depth_Lower = DEPHL,
      .keep = .keep
    ) |>
    return()
}
