# Load required libraries ----
library(sf)
library(tidyverse)
library(sfhelper)
library(rnaturalearth)
library(rnaturalearthdata)
library(mapproj)
library(ggspatial)
library(shadowtext)
library(ggrepel)
library(rlang)
library(data.table)
library(dtplyr)
library(leaflet)
library(janitor)
library(shiny)
library(readxl)
library(purrr)

`%notin%` <- negate(`%in%`)
